### ISSUE TITLE
TypeScript toggle doesn't work if basic code intel fallback is used

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph-typescript#141]
This is because the `activate` function does an early return before the toggle command is registered, and there is no logic to handle the toggle for basic code intel.

The toggle should still work, and ideally communicate in the tooltip or otherwise that basic code intel is used. 

cc @chrismwendt

**Comment by chrismwendt** [comment]
Perhaps we could hide the toggle when basic code intel is used?

**Comment by felixfbecker** [comment]
The toggle is there to allow disabling hovers mainly on PRs when code intel is unwanted, so it should work when basic code intel is used too

**Comment by chrismwendt** [comment]
Gotcha, I wonder if this applies to all the other languages, too.

**Comment by felixfbecker** [comment]
Definitely

**Comment by chrismwendt** [comment]
Have we gotten feedback about this for other languages? I don't recall off the top of my head.

**Comment by felixfbecker** [comment]
Not sure, I don't remember the feedback as langauge-specific. We heard the same feedback a lot of times (not usually mentioning any particular language)

**Comment by chrismwendt** [comment]
Oh, yup https://sourcegraph.slack.com/archives/C0W2E592M/p1550877960027100

> Too many popups, too much uploading of my content, and generally too complicated and noisy. I just want see green/red gutters for codecov coverage on GitHub, I don't want to reinvent GitHub.

This makes me wonder if it would be worth adding a global code intel enable/disable toggle (so we don't have to implement it multiple times).

**Comment by sqs** [comment]
@chrismwendt The toggle should just be implemented in https://sourcegraph.com/github.com/sourcegraph/lsp-client (and that should be used by all language extensions), and then it would not need to be implemented multiple times.

A global code intel enable/disable toggle would be bad because it would require the introduction of a new concept and API to know which hover/definition/references/etc. providers are "related to code intelligence" and disable those only. Unless you're thinking of something else.

**Comment by felixfbecker** [comment]
Agree. The toggle (and setting) always needs to be defined in package.json for each extension, so both `lsp-client` and `basic-code-intel` npm packages should support an option on what setting to listen to (could just use `${language}.enable` to make it consistent). They could both register the command implementation (since it's a oneliner) or that could be its own package.

**Comment by chrismwendt** [comment]
Sounds good, I was thinking of a toggle to disable all hover/def/ref providers, but there might be non-code-intel extensions that use those. There's no way that I can think of to tell if an arbitrary provider is "related to code intel".

The only blocker is that the Go extension will need https://github.com/sourcegraph/lsp-client/pull/11 (which in turn needs refactoring).

**Comment by ryan-blunden** [comment]
@felixfbecker I'm seeing this when clicking on the [TS] icon:

<img width="970" alt="Screen Shot 2019-06-12 at 3 47 05 PM" src="https://user-images.githubusercontent.com/133014/59391580-94bb7700-8d29-11e9-9f7c-46177ce0bfec.png">

Is that relevant for this issue or something else?

**Comment by felixfbecker** [comment]
Yes, that is exactly this issue.

**Comment by felixfbecker** [comment]
The toggle was removed.
