### ISSUE TITLE
typescript.sourcegraphUrl not allowed

### ISSUE THREAD

**Issue by ethankhall** [sourcegraph/sourcegraph-typescript#247]
I'm attempting to setup the typescript code intelligence, and when I get to the README steps to add `typescript.sourcegraphUrl` to the config, I add it and attempt to save. When I do the server sends back an error.

![Screen Shot 2019-09-30 at 4 58 22 PM](https://user-images.githubusercontent.com/794802/65924962-c4a78c80-e3a3-11e9-8542-0dc9d3fef66c.png)

What am I doing wrong in the setup?

**Comment by vanesa** [comment]
Hi @ethankhall, could you check if you don't already have a `typescript.sourcegraphUrl` property setup in either the global, organization, or user configurations?
